spring:
  application:
    name: helios
  datasource:
    url: jdbc:postgresql://localhost:5432/jobsdb?serverTimezone=Asia/Kolkata
    username: dev
    password: devpass
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        jdbc:
          time_zone: Asia/Kolkata
server:
  port: 9000