version: "3.8"
services:
  postgres:
    image: postgres:15
    container_name: job-scheduler-postgres
    environment:
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: devpass
      POSTGRES_DB: jobsdb
      TZ: Asia/Calcutta
      PGTZ: Asia/Kolkata
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata:
